export { fetchLangDictAction } from './redux-module';
export { geti18Next, geti18NextSync } from './utils/get-i18next';
export { getLocale } from './utils/get-locale';
export { setLocale } from './utils/set-locale';
export { fetchDictionary } from './utils/fetch-dictionary';
export { i18nextRequest } from './api/i18next-request';
export { getI18nextRequestEndpoint } from './utils/get-i18next-endpoint';
export { getLanguagesRequest } from './api/get-languages-request';
export { setHeadLang } from './utils/set-head-lang';
export * from './redux-module';
